"""
This module contains definitions of
constants for use in the project.
"""

# Energy conversion
KWH_TO_JOULES: float = 3.6e6
WH_TO_JOULES: float = KWH_TO_JOULES / 1000
JOULES_TO_KWH: float = 1 / KWH_TO_JOULES
JOULES_TO_WH: float = 1 / WH_TO_JOULES

# Fuel energy densities (J/kg)
ENERGY_DENSITY_GASOLINE: float = 44.4e6
ENERGY_DENSITY_DIESEL: float = 45.4e6
ENERGY_DENSITY_HYDROGEN: float = 130e6
ENERGY_DENSITY_ETHANOL: float = 26.8e6
ENERGY_DENSITY_METHANOL: float = 22.6e6
ENERGY_DENSITY_BIODIESEL: float = 37.8e6
ENERGY_DENSITY_METHANE: float = 53e6

# Fuel mass densities (kg/m^3)
DENSITY_GASOLINE: float = 742.9
DENSITY_DIESEL: float = 830.0
DENSITY_ETHANOL: float = 789.0
DENSITY_METHANOL: float = 791.3
DENSITY_BIODIESEL: float = 874.7
DENSITY_HYDROGEN_LIQUID: float = 70.85

BATTERY_EFFICIENCY_DEFAULT: float = 0.95
HYDROGEN_FUEL_CELL_EFFICIENCY_DEFAULT: float = 0.60

# Engine and motor default efficiencies
ELECTRIC_MOTOR_DEFAULT_EFFICIENCY: float = 0.85
GASOLINE_ENGINE_DEFAULT_EFFICIENCY: float = 0.35
DIESEL_ENGINE_DEFAULT_EFFICIENCY: float = 0.35
HYDROGEN_ENGINE_DEFAULT_EFFICIENCY: float = 0.35
ETHANOL_ENGINE_DEFAULT_EFFICIENCY: float = 0.35
METHANOL_ENGINE_DEFAULT_EFFICIENCY: float = 0.35
BIODIESEL_ENGINE_DEFAULT_EFFICIENCY: float = 0.35

ELECTRIC_GENERATOR_DEFAULT_EFFICIENCY: float = 0.85

BATTERY_DEFAULT_SOH: float = 1.0

# Gravimetric energy density for battery types (Wh/kg, converted to J/kg)
BATTERY_Al_AIR_ENERGY_DENSITY: float = 1300.0 * WH_TO_JOULES
BATTERY_Pb_ACID_ENERGY_DENSITY: float = 40.0 * WH_TO_JOULES
BATTERY_LiCo_ENERGY_DENSITY: float = 170.0 * WH_TO_JOULES
BATTERY_LiMn_ENERGY_DENSITY: float = 117.5 * WH_TO_JOULES
BATTERY_LiPh_ENERGY_DENSITY: float = 105.0 * WH_TO_JOULES
BATTERY_LiPo_ENERGY_DENSITY: float = 180.0 * WH_TO_JOULES
BATTERY_NiCd_ENERGY_DENSITY: float = 68.5 * WH_TO_JOULES
BATTERY_NiMH_ENERGY_DENSITY: float = 90.0 * WH_TO_JOULES
BATTERY_SOLID_STATE_ENERGY_DENSITY: float = 350.0 * WH_TO_JOULES
